import React from "react"
// styles
import pageStyles from "../styles/Home.module.css"
import notesStyles from "./Notes.module.css"
// components
import Head from "next/head"
import Footer from "../components/footer"
import Link from "next/link"
// services
import notesService from "../services/notes.service"

type TNotesPageProps = {
  postList: {
    id: string
    title: string
  }[]
}

const NotesPage: React.FC<TNotesPageProps> = ({ postList }) => {
  return (
    <div className={pageStyles.container}>
      <Head>
        <title>Create Next App </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={pageStyles.main}>
        {/* <h4 className={pageStyles.title}>Welcome to Notes testing page</h4> */}
        <br />

        <div>
          {postList?.map((post) => (
            <>
              <Link key={post.id} href={`/notes/${post.id}`}>
                <a className={notesStyles.link}>{post.title}</a>
              </Link>
            </>
          ))}
        </div>
      </main>
      <Footer />
    </div>
  )
}

export default NotesPage

export const getStaticProps = async () => {
  try {
    const client = notesService()
    const postList = client.getPostList()

    return {
      props: {
        postList,
      },
    }
  } catch (error) {
    return {
      props: { postList: null },
    }
  }
}
