import React from "react"
// styles
import styles from "../styles/Home.module.css"
// components
import Head from "next/head"
import Footer from "../components/footer"
import Link from "next/link"
// services
import notesService from "../services/notes.service"

type TNotesPageProps = {
  postList: {
    id: string
    title: string
  }[]
}

const NotesPage: React.FC<TNotesPageProps> = ({ postList }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Notion API testing page</h1>

        <div className={styles.grid}>
          {postList?.map((post) => (
            <Link key={post.id} href={`/notes/${post.id}`}>
              <a>{post.title}</a>
            </Link>
          ))}
        </div>
      </main>
      <Footer />
    </div>
  )
}

export default NotesPage

export const getStaticProps = async () => {
  try {
    const client = notesService()
    const postList = client.getPostList()

    return {
      props: {
        postList,
      },
    }
  } catch (error) {
    return {
      props: { postList: null },
    }
  }
}
