import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Footer from '../components/footer'
// services
import notionClient from '../services/notion'

export default ({ data }) => {
  console.log({ data })
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Notion API testing page
        </h1>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            andrzej
          </a>
        </div>
      </main>
      <Footer />
    </div>
  )
}

export const getStaticProps = async (context) => {
  try {
    const client = notionClient()
    const DGData = await client.getPostList()
    const postList = DGData.results
    console.log({ firstPostReference: postList[0] })
    const firstPostID = postList[0].id
    const firstPostData = await client.getPostById(firstPostID)
    console.log({ firstPostData, pageProps: firstPostData.pageInfo.properties })

    return {
      props: {
        data: {
          postList, firstPostData
        }
      }
    }
  } catch (error) {
    console.log(error)
    return {
      props: { data: null, error: 'error' }
    }
  }
}